# from http://jekyllrb.com/docs/continuous-integration/
language: ruby
rvm:
  - 2.2.4
# Assume bundler is being used
script:
  - bundle exec jekyll build
# branch whitelist, only for GitHub Pages
branches:
  only:
  - gh-pages
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
