# top level stuff
highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title
paginate: 5
safe: true
plugins: [jekyll-paginate, 'kramdown']

# edit here to achieve your personal greatness
url: https://fromseedtoslice.com
title: Seed to Slice
author: Jonathan Jones
description: A Home Grown Pizza Project
avatar: veggie-pizza-slice.png
google_analytics: UA-58456683-1
google_plus: JonathanJones646
email: jjones646+fromseedtoslice@gmail.com
github: jjones646
linkedin: joncjones93
keybase: jjones646

# needed for travis-ci build
exclude:
  - .gitignore
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock